# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 02 Oct 2017 20:59:44 +0000
*               @ALL          1
*               @user         8
